addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.9.27")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.6.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")